# Generated by Django 5.0.2 on 2024-02-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='admin_name',
            field=models.CharField(blank=True, max_length=10000),
        ),
    ]
