# Generated by Django 5.0.2 on 2024-02-20 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_admin_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10000)),
                ('email', models.CharField(max_length=100000)),
                ('message', models.CharField(max_length=100000000)),
            ],
        ),
        migrations.AlterField(
            model_name='user',
            name='admin_name',
            field=models.CharField(max_length=10000),
        ),
    ]
