# Generated by Django 5.0.2 on 2024-02-23 14:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authtoken', '0003_tokenproxy'),
        ('user', '0005_category_product_delete_admin_users'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin_users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('A_username', models.CharField(max_length=100000)),
                ('A_email', models.CharField(max_length=100000)),
                ('A_password', models.CharField(max_length=100000)),
                ('admin_token', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='authtoken.token')),
            ],
        ),
    ]
