# Generated by Django 5.0.2 on 2024-02-27 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_countrycode_phonenumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='P_quantity',
            field=models.PositiveIntegerField(default=99),
            preserve_default=False,
        ),
    ]
