# Generated by Django 5.0.2 on 2024-02-27 07:52

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_product_p_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('U_quantity', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)])),
                ('U_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.admin_users')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='user.product')),
            ],
        ),
    ]
