# Generated by Django 5.0.2 on 2024-02-27 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_chart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='U_quantity',
        ),
    ]
