# Generated by Django 5.0.2 on 2024-02-27 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_remove_chart_u_quantity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chart',
            name='product',
        ),
        migrations.AddField(
            model_name='chart',
            name='product',
            field=models.ManyToManyField(to='user.product'),
        ),
    ]
