# Generated by Django 5.0.2 on 2024-02-27 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_remove_chart_product_chart_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin_users',
            name='A_email',
            field=models.EmailField(max_length=254),
        ),
    ]
