# Generated by Django 5.0.2 on 2024-02-27 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_alter_admin_users_a_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chart',
            name='product',
            field=models.ManyToManyField(blank=True, to='user.product'),
        ),
    ]
